language: shell

os: windows

before_script:
# - choco install sqllocaldb
# - echo $HOME && "/c/Program Files/Microsoft SQL Server/140/Tools/Binn/SqlLocalDB.exe" create MSSQLLocalDb -s
- choco install mssqlserver2014-sqllocaldb
- powershell -Command "Set-ExecutionPolicy Bypass"

script:
- powershell -File build.ps1
