language: shell

os: windows

before_script:
# Use mssqlserver2014-sqllocaldb rather than sqllocaldb package which has an issue:
# https://dba.stackexchange.com/questions/191393/localdb-v14-creates-wrong-path-for-mdf-files
- choco install mssqlserver2014-sqllocaldb
- powershell -Command "Set-ExecutionPolicy Bypass"

script:
- powershell -File build.ps1
